/*******************************************************************************
 * Copyright (c) 2012 Cesar Yeep.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the BSD 3-Clause License
 * ("New BSD" or "BSD Simplified") which accompanies this distribution,
 * and is available at
 * http://opensource.org/licenses/BSD-3-Clause
 * 
 * Contributors:
 *     Cesar Yeep - initial API and implementation
 ******************************************************************************/
package edu.utep.cs.jasg.specificationGenerator.documentGenerator;

import org.jdom2.Element;

/** A beaver specification document generator. */
public class BeaverDocumentFactory extends ParserDocumentFactory {
	
	//TODO: modify implementation to support properties instead of methods
	public BeaverDocumentFactory(Element element, String template) {
		super(element,template);
	}

	//document outline template

	protected String documentHeader() {
		return "//parser file generated by JASG using "+getTemplateName()+" template\n";
	}
	
	//rule template

	protected String endOfRule() {
		return ";\n";
	}
	
	protected String definitionSymbol(){
		return "= ";
	}

	protected String elseSymbol() {
		return "\n  | ";
	}

	protected String idUseSeparator() {
		return ".";
	}

	protected String codeInit() {
		return " {: ";
	}

	protected String codeEnd() {
		return " :}";
	}

	
}
